In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [9]:
data = pd.read_csv('Iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
#dropping unwanted column

columns_to_drop = ['Id']
data_clean = data.drop(columns=columns_to_drop)

In [10]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [11]:
#segregating independent and dependent variables

input_cols = ['SepalLengthCm', 'SepalWidthCm','PetalLengthCm','PetalWidthCm']
output_cols = ['Species']

X= data_clean[input_cols]
Y= data_clean[output_cols]

In [12]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [13]:
Y

Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [14]:
print(X.shape, Y.shape)

(150, 4) (150, 1)


In [15]:
#shuffling data cleaning
from sklearn.utils import shuffle
data_clean = shuffle(data_clean, random_state=13)

In [16]:
#splitting data into train and test
split = int(0.7*data_clean.shape[0])
train_data=data_clean[:split]
test_data=data_clean[split:]
test_data = test_data.reset_index(drop=True)

In [17]:
#implementing decision tree
from sklearn.tree import DecisionTreeClassifier
sk_tree = DecisionTreeClassifier(criterion='entropy', max_depth=5)
sk_tree.fit(train_data[input_cols],train_data[output_cols])
y_pred= sk_tree.predict(test_data[input_cols])
print(y_pred)

['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor']


In [18]:
y_actual = test_data[output_cols]
y_actual = y_actual.values
y_actual = y_actual.reshape((-1,))

In [19]:
from sklearn import metrics
y_pred = sk_tree.predict(train_data[input_cols])
print("accuracy score: {0:.4f}\n".format(metrics.accuracy_score(train_data[output_cols],y_pred)))
print("Classification Report: \n {}\n".format(metrics.classification_report(train_data[output_cols],y_pred)))
print("Confusion Matrix: \n {}\n".format(metrics.confusion_matrix(train_data[output_cols],y_pred)))

accuracy score: 0.9905

Classification Report: 
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        35
Iris-versicolor       0.97      1.00      0.99        33
 Iris-virginica       1.00      0.97      0.99        37

       accuracy                           0.99       105
      macro avg       0.99      0.99      0.99       105
   weighted avg       0.99      0.99      0.99       105


Confusion Matrix: 
 [[35  0  0]
 [ 0 33  0]
 [ 0  1 36]]



In [20]:
# for test
y_pred = sk_tree.predict(test_data[input_cols])
print("Test Result:\n")
print("accuracy score: {0:.4f}\n".format(metrics.accuracy_score(y_actual,y_pred)))
print("Classification Report: \n {}\n".format(metrics.classification_report(y_actual,y_pred)))
print("Confusion Matrix: \n {}\n".format(metrics.confusion_matrix(y_actual,y_pred)))

Test Result:

accuracy score: 0.9778

Classification Report: 
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      0.94      0.97        17
 Iris-virginica       0.93      1.00      0.96        13

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45


Confusion Matrix: 
 [[15  0  0]
 [ 0 16  1]
 [ 0  0 13]]

